config/routes.rb
Messages::Application.routes.draw do
  resources :messages, :except => [:edit, :update]

  namespace :admin do
    resources :users
    resources :messages
  end
  
  devise_for :users

  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
  belongs_to :recipient, :class_name => "User", :foreign_key => "recipient_id"
  
  validates :subject, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  #has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id"
  #has_many :recieved_messages, :class_name => "Message", :foreign_key => "recipient_id"
  
  # TODO: beautify this!
  def messages
    Message.where("sender_id = ? OR recipient_id = ?", id, id)
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  load_and_authorize_resource
  
  # GET /admin/messages
  # GET /admin/messages.xml
  def index
    @admin_messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_messages }
    end
  end

  # GET /admin/messages/1
  # GET /admin/messages/1.xml
  def show
    @admin_message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_message }
    end
  end

  # GET /admin/messages/new
  # GET /admin/messages/new.xml
  def new
    @admin_message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_message }
    end
  end

  # GET /admin/messages/1/edit
  def edit
    @admin_message = Message.find(params[:id])
  end

  # POST /admin/messages
  # POST /admin/messages.xml
  def create
    @admin_message = Message.new(params[:message])

    respond_to do |format|
      if @admin_message.save
        format.html { redirect_to([:admin, @admin_message], :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @admin_message, :status => :created, :location => @admin_message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/messages/1
  # PUT /admin/messages/1.xml
  def update
    @admin_message = Message.find(params[:id])

    respond_to do |format|
      if @admin_message.update_attributes(params[:message])
        format.html { redirect_to([:admin, @admin_message], :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/messages/1
  # DELETE /admin/messages/1.xml
  def destroy
    @admin_message = Message.find(params[:id])
    @admin_message.destroy

    respond_to do |format|
      format.html { redirect_to(admin_messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource
  
  # GET /admin/users
  # GET /admin/users.xml
  def index
    @admin_users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.xml
  def show
    @admin_user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.xml
  def new
    @admin_user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @admin_user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.xml
  def create
    @admin_user = User.new(params[:user])

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to([:admin, @admin_user], :notice => 'User was successfully created.') }
        format.xml  { render :xml => @admin_user, :status => :created, :location => @admin_user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml
  def update
    @admin_user = User.find(params[:id])

    respond_to do |format|
      if @admin_user.update_attributes(params[:user])
        format.html { redirect_to([:admin, @admin_user], :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml
  def destroy
    @admin_user = User.find(params[:id])
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to(admin_users_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
    @messages = current_user.messages.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = current_user.messages.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = current_user.messages.new(params[:message])
    
    # hack to overwrite sender again
    @message.sender = current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = current_user.messages.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/messages/_form.html.haml
= form_for [:admin, @admin_message] do |f|
  -if @admin_message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_message.errors.count, "error")} prohibited this admin_message from being saved:"
      %ul
        - @admin_message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :sender_id
    = f.text_field :sender_id
  .field
    = f.label :recipient_id
    = f.text_field :recipient_id
  .field
    = f.label :subject
    = f.text_field :subject
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/admin/messages/edit.html.haml
%h1 Editing admin_message

= render 'form'

= link_to 'Show', [:admin, @admin_message]
\|
= link_to 'Back', admin_messages_path

app/views/admin/messages/index.html.haml
%h1 Listing admin_messages

%table
  %tr
    %th Sender
    %th Recipient
    %th Subject
    %th Body
    %th
    %th
    %th

  - @admin_messages.each do |admin_message|
    %tr
      %td= admin_message.sender_id
      %td= admin_message.recipient_id
      %td= admin_message.subject
      %td= admin_message.body
      %td= link_to 'Show', admin_message_path(admin_message)
      %td= link_to 'Edit', edit_admin_message_path(admin_message)
      %td= link_to 'Destroy', admin_message_path(admin_message), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Message', new_admin_message_path

app/views/admin/messages/new.html.haml
%h1 New admin_message

= render 'form'

= link_to 'Back', admin_messages_path

app/views/admin/messages/show.html.haml
%p
  %b Sender:
  = @admin_message.sender_id
%p
  %b Recipient:
  = @admin_message.recipient_id
%p
  %b Subject:
  = @admin_message.subject
%p
  %b Body:
  = @admin_message.body

= link_to 'Edit', edit_admin_message_path(@admin_message)
\|
= link_to 'Back', admin_messages_path

app/views/admin/users/_form.html.haml
= form_for [:admin, @admin_user] do |f|
  -if @admin_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_user.errors.count, "error")} prohibited this admin_user from being saved:"
      %ul
        - @admin_user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/admin/users/edit.html.haml
%h1 Editing admin_user

= render 'form'

= link_to 'Show', [:admin, @admin_user]
\|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.haml
%h1 Listing admin_users

%table
  %tr
    %th Email
    %th Registered at
    %th Sign in count
    %th Current sign in at
    %th
    %th
    %th

  - @admin_users.each do |admin_user|
    %tr
      %td= admin_user.email
      %td= admin_user.created_at
      %td= admin_user.sign_in_count
      %td= admin_user.current_sign_in_at
      %td= link_to 'Show', admin_user_path(admin_user)
      %td= link_to 'Edit', edit_admin_user_path(admin_user)
      %td= link_to 'Destroy', admin_user_path(admin_user), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.haml
%h1 New admin_user

= render 'form'

= link_to 'Back', admin_users_path

app/views/admin/users/show.html.haml
%p
  %strong email:
  = @admin_user.email  
%p
  %strong sign_in_count:
  = @admin_user.sign_in_count
%p
  %strong current_sign_in_at:
  = @admin_user.current_sign_in_at
%p
  %strong last_sign_in_at:
  = @admin_user.last_sign_in_at
%p
  %strong current_sign_in_ip:
  = @admin_user.current_sign_in_ip
%p
  %strong last_sign_in_ip:
  = @admin_user.last_sign_in_ip
%p
  %strong created_at:
  = @admin_user.created_at
%p
  %strong updated_at:
  = @admin_user.updated_at

= link_to 'Edit', edit_admin_user_path(@admin_user)
\|
= link_to 'Back', admin_users_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Messaging
  = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
  = stylesheet_link_tag 'compiled/print.css', :media => 'print'
  /[if IE]
    = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
  = javascript_include_tag :defaults
  = csrf_meta_tag
%body.bp.two-col
  #container
    #header
      %h2 Messages
      #login
        - if user_signed_in?
          = "Signed in as #{current_user.email}"
          = link_to "Log out", destroy_user_session_path
        - else
          = link_to "Sign up", new_user_registration_path
          or 
          = link_to "Sign in", new_user_session_path
      .clear
      #navigation
        = link_to "Messages", messages_path
    %hr.clear.space
    -if notice
      .success= notice
    -if alert
      .error= alert
    =yield

app/views/messages/_form.html.haml
= form_for @message do |f|
  -if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :recipient_id
    %br
    = f.text_field :recipient_id
  .field
    = f.label :subject
    %br
    = f.text_field :subject
  .field
    = f.label :body
    %br
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %tr
    %th Sender
    %th Recipient
    %th Subject
    %th Body
    %th
    %th

  - @messages.each do |message|
    %tr
      %td= message.sender_id
      %td= message.recipient_id
      %td= message.subject
      %td= message.body
      %td= link_to 'Show', message
      %td= link_to 'Destroy', message, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Message', new_message_path

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p
  %b Sender:
  = @message.sender_id
%p
  %b Recipient:
  = @message.recipient_id
%p
  %b Subject:
  = @message.subject
%p
  %b Body:
  = @message.body

= link_to 'Back', messages_path

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml